//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to compile the expression [{0}]. {1}.
        /// </summary>
        internal static string IDS_ERR_COMPILERERROR {
            get {
                return ResourceManager.GetString("IDS_ERR_COMPILERERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty tag value..
        /// </summary>
        internal static string IDS_ERR_EMPTYTAGAVLUE {
            get {
                return ResourceManager.GetString("IDS_ERR_EMPTYTAGAVLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inavlid element type [{0}]..
        /// </summary>
        internal static string IDS_ERR_INVALIDELEMENTTYPE {
            get {
                return ResourceManager.GetString("IDS_ERR_INVALIDELEMENTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid journal type [{0}]..
        /// </summary>
        internal static string IDS_ERR_INVALIDJOURNALTYPE {
            get {
                return ResourceManager.GetString("IDS_ERR_INVALIDJOURNALTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Valid month value must be between 1 to 12 not [{0}]..
        /// </summary>
        internal static string IDS_ERR_MONTHOUTOFRANGE {
            get {
                return ResourceManager.GetString("IDS_ERR_MONTHOUTOFRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на april.
        /// </summary>
        internal static string IDS_VAL_APRIL {
            get {
                return ResourceManager.GetString("IDS_VAL_APRIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на august.
        /// </summary>
        internal static string IDS_VAL_AUGUST {
            get {
                return ResourceManager.GetString("IDS_VAL_AUGUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на december.
        /// </summary>
        internal static string IDS_VAL_DECEMBER {
            get {
                return ResourceManager.GetString("IDS_VAL_DECEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на february.
        /// </summary>
        internal static string IDS_VAL_FEBRUARY {
            get {
                return ResourceManager.GetString("IDS_VAL_FEBRUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на january.
        /// </summary>
        internal static string IDS_VAL_JANUARY {
            get {
                return ResourceManager.GetString("IDS_VAL_JANUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на july.
        /// </summary>
        internal static string IDS_VAL_JULY {
            get {
                return ResourceManager.GetString("IDS_VAL_JULY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на june.
        /// </summary>
        internal static string IDS_VAL_JUNE {
            get {
                return ResourceManager.GetString("IDS_VAL_JUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на march.
        /// </summary>
        internal static string IDS_VAL_MARCH {
            get {
                return ResourceManager.GetString("IDS_VAL_MARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на may.
        /// </summary>
        internal static string IDS_VAL_MAY {
            get {
                return ResourceManager.GetString("IDS_VAL_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на november.
        /// </summary>
        internal static string IDS_VAL_NOVEMBER {
            get {
                return ResourceManager.GetString("IDS_VAL_NOVEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на october.
        /// </summary>
        internal static string IDS_VAL_OCTOBER {
            get {
                return ResourceManager.GetString("IDS_VAL_OCTOBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на september.
        /// </summary>
        internal static string IDS_VAL_SEPTEMBER {
            get {
                return ResourceManager.GetString("IDS_VAL_SEPTEMBER", resourceCulture);
            }
        }
    }
}
